model_params:
  temperature: 0.7
  top_p: 0.9
file_paths:
  pdf_directory: "C:/Users/jiaod/Desktop/learning/paper/paper_summary/test_pdf"
  notes_directory: "C:/Users/jiaod/Desktop/learning/paper/paper_summary/test_notes"
prompt_template: "请总结以下文献的核心结论、研究方法和关键贡献："
deepseek:
  api_key: "sk-bc118e7928914e5bb0bc75555eabd5d4"
  